name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop 
  pull_request:
    branches:
      - main
      - develop 

jobs:
  # Job for the Backend Continuous Integration
  backend_ci:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4 
        name: Checkout Code

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4 # Sets up Node.js
        with:
          node-version: '20' 
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json 

      - name: Install Backend Dependencies
        run: cd backend && npm install 

      - name: Run Backend Lint
        run: cd backend && npm run lint 
       
      - name: Run Backend Tests
        run: cd backend && npm test

  # Job for the Frontend Continuous Integration
  frontend_ci:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: cd frontend && npm install # Navigates to frontend and installs packages

      - name: Run Frontend Lint
        run: cd frontend && npm run lint 

      - name: Run Frontend Tests
        run: cd frontend && npm test 
