name: Trigger auto deployment for stm-backend-92cyrveb

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/stm-backend-92cyrveb-AutoDeployTrigger-8bc15d64-a4a3-4294-8bb7-dfc496c1801e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.STMBACKEND92CYRVEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.STMBACKEND92CYRVEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.STMBACKEND92CYRVEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: rm06stm92cyrveb.azurecr.io
          registryUsername: ${{ secrets.STMBACKEND92CYRVEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STMBACKEND92CYRVEB_REGISTRY_PASSWORD }}
          containerAppName: stm-backend-92cyrveb
          resourceGroup: simple-task-manager-rg
          imageToBuild: rm06stm92cyrveb.azurecr.io/stm-backend-92cyrveb:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


